<?php

/**
 * @file
 * The main Islandora Usage Stats Charts module file.
 */

// Includes blocks.
require_once dirname(__FILE__) . '/includes/blocks.inc';

/**
 * Implements hook_menu().
 */
function islandora_usage_stats_charts_menu() {
  $items['admin/islandora/tools/islandora_usage_stats_charts'] = array(
    'title' => 'Islandora Usage Stats Charts',
    'description' => 'Configure the Islandora Usage Stats Charts module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_usage_stats_charts_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Admin form definition.
 */
function islandora_usage_stats_charts_admin_settings() {
  $form = array();
  $form['islandora_usage_stats_charts_javascript_url'] = array(
    '#type' => 'textfield',
    '#size' => '100',
    '#title' => t('Chart.js library URL'),
    '#default_value' => variable_get('islandora_usage_stats_charts_javascript_url', 'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js'),
  );
  $form['islandora_usage_stats_charts_views_color'] = array(
    '#type' => 'textfield',
    '#size' => '10',
    '#title' => t('Color of "views" bar in chart'),
    '#default_value' => variable_get('islandora_usage_stats_charts_views_color', '#002db3'),
    '#description' => t('You can use hexadecimal, RGB, or HSL color values.'),
  );
  $form['islandora_usage_stats_charts_downloads_color'] = array(
    '#type' => 'textfield',
    '#size' => '10',
    '#title' => t('Color of "downloads" bar in chart'),
    '#default_value' => variable_get('islandora_usage_stats_charts_downloads_color', '#99b3ff'),
    '#description' => t('You can use hexadecimal, RGB, or HSL color values.'),
  );
  $form['islandora_usage_stats_charts_max_chart_width'] = array(
    '#type' => 'textfield',
    '#size' => '10',
    '#title' => t('Maximum width of chart, with units'),
    '#default_value' => variable_get('islandora_usage_stats_charts_max_chart_width', '50em'),
    '#description' => t('E.g. 50em, 400px. Leave blank to allow the chart to fill the parent div.'),
  );
  $form['islandora_usage_stats_charts_limit_chart_height'] = array(
    '#type' => 'checkbox',
    '#title' => t('Limit chart height to its width'),
    '#default_value' => variable_get('islandora_usage_stats_charts_limit_chart_height', 1),
    '#description' => t("Wide variations in monthly usage stats can result in charts that have a very high vertical dimension. Checking this option will ensure that the chart's height does not exceed its width."),
  );
  $form['islandora_usage_stats_charts_collapsed'] = array(
    '#type' => 'checkbox',
    '#title' => t('Collapse chart blocks by default'),
    '#default_value' => variable_get('islandora_usage_stats_charts_collapsed', 1),
    '#description' => t("Users can still toggle the collapse."),
  );
  $form['islandora_usage_stats_charts_months_to_show'] = array(
    '#type' => 'textfield',
    '#size' => '10',
    '#title' => t("Maximum number of months' data to show in chart"),
    '#default_value' => variable_get('islandora_usage_stats_charts_months_to_show', '6'),
    '#description' => t("If the number of months for which data is available is lower than this setting, the lower number of months is used. Stats are shown from the day of the first month corresponding to the day the user views the chart; for example, if this setting is '6' and the chart is viewed on July 10th, the first month's stats will start at February 10th."),
  );
  $form['islandora_usage_stats_charts_show_datastreams_downloads'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show datastream download stats'),
    '#default_value' => variable_get('islandora_usage_stats_charts_show_datastreams_downloads', 0),
  );
  if (module_exists('islandora_usage_stats_csv')) {
    $other_setting_note = t("This setting should be the same as the 'Omit from datastream reports' setting used by Islandora Usage Stats CSV.");
  }
  else {
    $other_setting_note = '';
  }
  $form['islandora_usage_stats_charts_dsids_to_skip'] = array(
    '#type' => 'textfield',
    '#size' => '100',
    '#title' => t('Omit from downloads stats'),
    '#default_value' => variable_get('islandora_usage_stats_charts_dsids_to_skip', 'RELS-EXT,RELS-INT,TECHMD,MODS,DC'),
    '#description' => t("Comma-separated list of datastream IDs to exclude from 'downloads' usage stats. All other datastreams will be included. If left blank, all datastreams will be included. !other_setting_note", array('!other_setting_note' => $other_setting_note)),
  );
  return system_settings_form($form);
}

/**
 * Implements hook_theme().
 */
function islandora_usage_stats_charts_theme() {
  return array(
    'islandora_usage_stats_charts' => array(
      'variables' => array(
        'collapsed' => NULL,
        'csv_link' => NULL,
      ),
      'path' => drupal_get_path('module', 'islandora_usage_stats_charts') . '/theme',
      'template' => 'islandora_usage_stats_charts',
    ),
  );
}
