<?php

/**
 * @file
 * The main Islandora Usage Stats Charts module file.
 */

// Includes blocks.
require_once dirname(__FILE__) . '/includes/blocks.inc';

/**
 * Implements hook_menu().
 */
function islandora_usage_stats_charts_menu() {
  $items['admin/islandora/tools/islandora_usage_stats_charts'] = array(
    'title' => 'Islandora Usage Stats Charts',
    'description' => 'Configure the Islandora Usage Stats Charts module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_usage_stats_charts_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Admin form definition.
 */
function islandora_usage_stats_charts_admin_settings() {
  $form = array();
  $form['islandora_usage_stats_charts_javascript_url'] = array(
    '#type' => 'textfield',
    '#size' => '100',
    '#title' => t('Chart.js library URL'),
    '#default_value' => variable_get('islandora_usage_stats_charts_javascript_url', 'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js'),
  );
  $form['islandora_usage_stats_charts_views_color'] = array(
    '#type' => 'textfield',
    '#size' => '10',
    '#title' => t('Color of "views" bar in chart'),
    '#default_value' => variable_get('islandora_usage_stats_charts_views_color', '#002db3'),
    '#description' => t('You can use hexadecimal, RGB, or HSL color values.'),
  );
  $form['islandora_usage_stats_charts_downloads_color'] = array(
    '#type' => 'textfield',
    '#size' => '10',
    '#title' => t('Color of "downloads" bar in chart'),
    '#default_value' => variable_get('islandora_usage_stats_charts_downloads_color', '#99b3ff'),
    '#description' => t('You can use hexadecimal, RGB, or HSL color values.'),
  );
  $form['islandora_usage_stats_charts_limit_chart_height'] = array(
    '#type' => 'checkbox',
    '#title' => t('Limit chart height to its width'),
    '#default_value' => variable_get('islandora_usage_stats_charts_limit_chart_height', 1),
    '#description' => t("Wide variations in monthly usage stats can result in charts that have a very high vertical dimension. Checking this option will ensure that the chart's height does not exceed its width."),
  );
  $form['islandora_usage_stats_charts_collapsed'] = array(
    '#type' => 'checkbox',
    '#title' => t('Collapse chart blocks by default'),
    '#default_value' => variable_get('islandora_usage_stats_charts_collapsed', 1),
    '#description' => t("Users can still toggle the collapse."),
  );
  $form['islandora_usage_stats_charts_months_to_show'] = array(
    '#type' => 'textfield',
    '#size' => '10',
    '#title' => t("Number of months' data to show in chart"),
    '#default_value' => variable_get('islandora_usage_stats_charts_months_to_show', '6'),
  );
  $form['islandora_usage_stats_charts_show_datastreams_downloads'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show datastream download stats'),
    '#default_value' => variable_get('islandora_usage_stats_charts_show_datastreams_downloads', 0),
  );
  return system_settings_form($form);
}

/**
 * Implements hook_theme().
 */
function islandora_usage_stats_charts_theme() {
  return array(
    'islandora_usage_stats_charts' => array(
      'variables' => array(
        'collapsed' => NULL,
      ),
      'path' => drupal_get_path('module', 'islandora_usage_stats_charts') . '/theme',
      'template' => 'islandora_usage_stats_charts',
    ),
  );
}
