<?php

/**
 * @file
 * This file contains all install related hooks.
 */

/**
 * Implements hook_uninstall().
 */
function islandora_usage_stats_charts_uninstall() {
  $variables = array(
    'islandora_usage_stats_charts_collapsed',
    'islandora_usage_stats_charts_show_datastreams_downloads',
    'islandora_usage_stats_charts_javascript_url',
    'islandora_usage_stats_charts_views_color',
    'islandora_usage_stats_charts_downloads_color',
  );
  array_walk($variables, 'variable_del');
}
